### ISSUE TITLE
Does not detect changes when common.props updated under Linux/3.1.100 sdk

### ISSUE THREAD

**Issue by IgorFedchenko** [petabridge/Incrementalist#106]
Repro is here: https://github.com/akkadotnet/akka.net/pull/4219
No updates detected: https://dev.azure.com/dotnet/Akka.NET/_build/results?buildId=28736&view=logs&jobId=d3d8bb3a-a87f-5af3-6a16-90b99d49172b&j=d3d8bb3a-a87f-5af3-6a16-90b99d49172b&t=1d19db56-c24e-5fbb-3f13-e91c53ee1789

### Summary

Looking at the repro in Akka.NET project, this should reproduce the problem:
- Have project targeting `netcoreapp3.1` (2.1 should also work)
- Make change in `common.props` file, that is referenced from `csproj` file of the project
- Run incrementalist of version `0.2.1` to check the changes under Linux using dotnet version `3.1.100`.

**Expected:** At least one project, referencing updated props file, should be detected as changed
**Actual:** No changes detected.

**Comment by IgorFedchenko** [comment]
Hmm, actually, updated build system in this repo to `v.3.1.100` should also meet this bug - we have tests that verifying `common.props` changes detection, so they should fail on CI after such update. Let me try

**Comment by IgorFedchenko** [comment]
Nope, it works. Either tests do not reproduce the actual issue, either I am looking at the wrong place.

Need to setup docker container with working Incrementalist, clone Akka.NET repo, make tmp branch with `common.props` changed and see the changed projects list.

**Comment by Aaronontheweb** [comment]
Roslyn upgrade definitely did not help - can see that here: https://github.com/akkadotnet/akka.net/pull/4187/checks?check_run_id=446814829
